export const ActionTypes = {
  SET_ARTICLE: "SET_ARTICLE",
  SET_LOADING: "SET_LOADING",
  SET_ARTICLE_BOOKMARKS: "SET_ARTICLE_BOOKMARKS",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
};
